/* Shared agricultural catalog + localization seeds consumed by both GIS and LIMS. */
(function(global){
  "use strict";
  const I18N={
    en:{soil:"Soil",clay:"Clay",vegetables:"Vegetables",fruits:"Fruits",farm:"Farm",farms:"Farms",pathology:"Pathology / Diseases",seedOil:"Seed Oil",fieldCrops:"Field Crops",trees:"Trees",map:"Map & Farms",basemap:"Basemap",overlay:"Data overlay",laboratory:"Laboratory Analytics",history:"Farm History",analytics:"Monthly Farm Analytics",search:"Search plants…",planner:"5-Year Strategic Crop Planning & Rotation",finance:"Financial Ledger",engineer:"Technical Engineer on Duty",language:"SOM | ENG"},
    so:{soil:"Ciid",clay:"Dhoobo",vegetables:"Khudaar",fruits:"Midho",farm:"Beer",farms:"Beeraha",pathology:"Cudurada",seedOil:"Saliidda Abuurka",fieldCrops:"Dalagyada Beeraha",trees:"Geedaha",map:"Khariidadda & Beeraha",basemap:"Khariidadda Hoose",overlay:"Lakabka Xogta",laboratory:"Falanqaynta Shaybaarka",history:"Taariikhda Beeraha",analytics:"Falanqaynta Billaha Beeraha",search:"Raadi dhirta…",planner:"Qorshaha Wareegga Dalagga 5 Sano",finance:"Diiwaanka Maaliyadda",engineer:"Injineerka Farsamada ee Shaqada",language:"SOM | ENG"}
  };
  const profiles={
    tomato:{category:"Vegetables",family:"Solanaceae",rootDepth:"Deep",nitrogenDemand:"Heavy Feeder",minPh:5.5,maxPh:7.5,maturityDays:90,seasons:["Gu","Deyr"],color:"#ef4444",pathologies:[["Bacterial Wilt","Ralstonia solanacearum","Rapid green wilt; vascular browning","Isolate beds and sanitize tools","Use clean transplants, resistant material and non-solanaceous rotation."],["Tomato Leafminer","Tuta absoluta","Leaf mines; fruit pinholes","Remove mined leaves and monitor pheromone traps","Use exclusion, biological control and selective registered controls at threshold."]]},
    onion:{category:"Vegetables",family:"Amaryllidaceae",rootDepth:"Shallow",nitrogenDemand:"Heavy Feeder",minPh:6,maxPh:7.2,maturityDays:110,seasons:["Deyr","Jilaal"],color:"#a78bfa",pathologies:[["Purple Blotch","Alternaria porri","Purple concentric lesions; leaf collapse","Remove infected leaves and reduce canopy humidity","Use clean seed, rotation and locally registered protectants."],["Downy Mildew","Peronospora destructor","Pale leaf patches; purple-gray sporulation","Avoid evening irrigation","Use airflow, rotation and weather-led protection."]]},
    pepper:{category:"Vegetables",family:"Solanaceae",rootDepth:"Medium",nitrogenDemand:"Heavy Feeder",minPh:5.8,maxPh:7,maturityDays:95,seasons:["Gu","Deyr"],color:"#dc2626",pathologies:[["Bacterial Spot","Xanthomonas species complex","Water-soaked leaf spots; scabby fruit","Remove infected transplants","Use clean seed and integrated copper-tolerant programs."],["Phytophthora Blight","Phytophthora capsici","Dark collar lesions; sudden wilt","Improve drainage and stop runoff","Use raised beds, resistant material and registered oomycete controls."]]},
    cabbage:{category:"Vegetables",family:"Brassicaceae",rootDepth:"Shallow",nitrogenDemand:"Heavy Feeder",minPh:6,maxPh:7.5,maturityDays:85,seasons:["Deyr","Jilaal"],color:"#14b8a6",pathologies:[["Black Rot","Xanthomonas campestris pv. campestris","V-shaped lesions; black veins","Remove infected residue","Use clean treated seed and rotate brassicas."],["Diamondback Moth","Plutella xylostella","Window-pane feeding; green larvae","Scout weekly and conserve parasitoids","Use netting, Bt and selective registered products at threshold."]]},
    carrot:{category:"Vegetables",family:"Apiaceae",rootDepth:"Medium",nitrogenDemand:"Light Feeder",minPh:6,maxPh:7,maturityDays:80,seasons:["Deyr","Jilaal"],color:"#fb923c",pathologies:[["Alternaria Leaf Blight","Alternaria dauci","Brown leaflet lesions; canopy collapse","Remove infected tops","Use clean seed, rotation and protectants where needed."],["Root-knot Nematode","Meloidogyne species","Forked roots; root galls","Prevent infested soil movement","Rotate poor hosts and use approved soil-health measures."]]},
    potato:{category:"Vegetables",family:"Solanaceae",rootDepth:"Shallow",nitrogenDemand:"Heavy Feeder",minPh:5,maxPh:6.5,maturityDays:100,seasons:["Deyr","Jilaal"],color:"#ca8a04",pathologies:[["Late Blight","Phytophthora infestans","Water-soaked lesions; tuber rot","Destroy infected haulms","Use certified seed and forecast-led registered protection."],["Bacterial Wilt","Ralstonia solanacearum","Sudden wilt; vascular ooze","Quarantine seed lots","Use certified seed, clean water and long rotation."]]},
    sweetpotato:{category:"Vegetables",family:"Convolvulaceae",rootDepth:"Deep",nitrogenDemand:"Heavy Feeder",minPh:5.5,maxPh:6.8,maturityDays:115,seasons:["Gu","Deyr"],color:"#c2410c",pathologies:[["Sweet Potato Weevil","Cylas formicarius","Cracked tunneled roots; bitter damage","Destroy residues and hill exposed roots","Use clean vines, pheromone monitoring and timely harvest."],["Sweet Potato Virus Disease","SPFMV/SPCSV complex","Mosaic; severe stunting","Rogue affected plants","Use virus-tested vines and manage vectors."]]},
    cucumber:{category:"Vegetables",family:"Cucurbitaceae",rootDepth:"Shallow",nitrogenDemand:"Heavy Feeder",minPh:5.8,maxPh:7,maturityDays:60,seasons:["Gu","Deyr"],color:"#2dd4bf",pathologies:[["Powdery Mildew","Podosphaera xanthii","White colonies; canopy decline","Improve airflow","Use resistant varieties and resistance-managed controls."],["Cucumber Mosaic","Cucumber mosaic virus","Mosaic leaves; malformed fruit","Rogue symptoms and weeds","Use clean seed and integrated aphid management."]]},
    watermelon:{category:"Vegetables",family:"Cucurbitaceae",rootDepth:"Deep",nitrogenDemand:"Heavy Feeder",minPh:5.5,maxPh:7.5,maturityDays:85,seasons:["Gu","Xagaa"],color:"#f43f5e",pathologies:[["Fusarium Wilt","Fusarium oxysporum f. sp. niveum","One-sided vine wilt; brown vessels","Remove vines and prevent soil transfer","Use resistant varieties, grafting and long rotation."],["Gummy Stem Blight","Stagonosporopsis species","Brown lesions; gummy stem cankers","Remove infected residue","Use clean seed, drip irrigation and resistance-managed controls."]]},
    pumpkin:{category:"Vegetables",family:"Cucurbitaceae",rootDepth:"Deep",nitrogenDemand:"Heavy Feeder",minPh:5.8,maxPh:7.5,maturityDays:105,seasons:["Gu","Deyr"],color:"#ea580c",pathologies:[["Powdery Mildew","Podosphaera xanthii","White colonies; leaf senescence","Remove severe leaves","Use tolerant cultivars and registered mildew controls."],["Cucurbit Mosaic","ZYMV/WMV complex","Yellow mosaic; distorted fruit","Rogue symptoms and volunteer hosts","Use clean seed and integrated vector management."]]},
    eggplant:{category:"Vegetables",family:"Solanaceae",rootDepth:"Deep",nitrogenDemand:"Heavy Feeder",minPh:5.5,maxPh:7.2,maturityDays:100,seasons:["Gu","Deyr"],color:"#7c3aed",pathologies:[["Bacterial Wilt","Ralstonia solanacearum","Rapid wilt; bacterial streaming","Remove roots and isolate irrigation","Use resistant rootstocks and non-host rotation."],["Fruit and Shoot Borer","Leucinodes orbonalis","Wilted shoots; bored fruit","Remove infested shoots","Use netting, pheromone monitoring and selective controls."]]},
    okra:{category:"Vegetables",family:"Malvaceae",rootDepth:"Deep",nitrogenDemand:"Light Feeder",minPh:6,maxPh:7.5,maturityDays:60,seasons:["Gu","Xagaa"],color:"#22c55e",pathologies:[["Yellow Vein Mosaic","Begomovirus complex","Yellow vein network; small pods","Rogue early infections","Use tolerant varieties and manage whitefly vectors."],["Okra Leaf Spot","Cercospora species","Brown leaf spots; defoliation","Remove infected residue","Use clean seed, airflow and registered protectants when necessary."]]},
    lettuce:{category:"Vegetables",family:"Asteraceae",rootDepth:"Shallow",nitrogenDemand:"Heavy Feeder",minPh:6,maxPh:7,maturityDays:50,seasons:["Deyr","Jilaal"],color:"#86efac",pathologies:[["Downy Mildew","Bremia lactucae","Angular yellow patches; white underside growth","Lower night humidity","Use resistant cultivars and locally registered controls."],["Bottom Rot","Rhizoctonia solani","Lower leaf decay; head collapse","Improve drainage and sanitation","Rotate and avoid soil contact with marketable leaves."]]},
    spinach:{category:"Vegetables",family:"Amaranthaceae",rootDepth:"Shallow",nitrogenDemand:"Heavy Feeder",minPh:6,maxPh:7.5,maturityDays:45,seasons:["Deyr","Jilaal"],color:"#15803d",pathologies:[["Stemphylium Leaf Spot","Stemphylium complex","Gray-brown spots; merged lesions","Remove residues","Use clean seed, rotation and avoid overhead irrigation."],["Spinach Downy Mildew","Peronospora effusa","Yellow patches; purple-gray growth","Remove affected leaves","Use resistant varieties and control humidity."]]},
    bean:{category:"Vegetables",family:"Fabaceae",rootDepth:"Medium",nitrogenDemand:"Nitrogen Fixer",minPh:5.5,maxPh:7.5,maturityDays:75,seasons:["Gu","Deyr"],color:"#10b981",pathologies:[["Bean Rust","Uromyces appendiculatus","Brown pustules; defoliation","Remove severe leaves","Use resistant clean seed and monitor thresholds."],["Angular Leaf Spot","Pseudocercospora griseola","Angular lesions; pod spots","Remove residue","Use clean resistant seed and crop rotation."]]},
    pea:{category:"Vegetables",family:"Fabaceae",rootDepth:"Medium",nitrogenDemand:"Nitrogen Fixer",minPh:6,maxPh:7.5,maturityDays:70,seasons:["Jilaal","Rabi"],color:"#4ade80",pathologies:[["Pea Powdery Mildew","Erysiphe pisi","White leaf powder; leaf drying","Remove infected residue","Use resistant cultivars and approved controls."],["Pea Root Rot","Aphanomyces/Fusarium complex","Brown roots; patchy wilt","Improve drainage","Use clean seed and long rotation."]]},
    mango:{category:"Fruits",family:"Anacardiaceae",rootDepth:"Deep",nitrogenDemand:"Light Feeder",minPh:5.5,maxPh:8,maturityDays:950,seasons:["Gu establishment"],color:"#fbbf24",pathologies:[["Anthracnose","Colletotrichum gloeosporioides","Black fruit lesions; blossom blight","Remove mummified fruit","Improve canopy drying and protect bloom during wet risk."],["Powdery Mildew","Oidium mangiferae","White flower powder; poor set","Open canopy airflow","Use locally registered mildew controls at bloom."]]},
    banana:{category:"Fruits",family:"Musaceae",rootDepth:"Shallow",nitrogenDemand:"Heavy Feeder",minPh:5.5,maxPh:7.5,maturityDays:350,seasons:["Year-round irrigation"],color:"#fde047",pathologies:[["Black Sigatoka","Pseudocercospora fijiensis","Dark streaks; leaf collapse","Remove badly spotted leaves","Use resistant material and resistance-managed protection."],["Fusarium Wilt TR4","Fusarium oxysporum f. sp. cubense","Yellow collapse; vascular browning","Quarantine affected mats","Use certified resistant planting material."]]},
    citrus:{category:"Fruits",family:"Rutaceae",rootDepth:"Deep",nitrogenDemand:"Heavy Feeder",minPh:5.5,maxPh:7.5,maturityDays:730,seasons:["Gu establishment"],color:"#fb923c",pathologies:[["Citrus Greening (HLB)","Candidatus Liberibacter","Asymmetric mottling; lopsided fruit","Remove confirmed source trees","Use certified stock and coordinated psyllid management."],["Citrus Canker","Xanthomonas citri","Raised lesions; yellow halos","Sanitize tools and prune dry","Use windbreaks and registered copper guidance."]]},
    avocado:{category:"Fruits",family:"Lauraceae",rootDepth:"Deep",nitrogenDemand:"Heavy Feeder",minPh:5.5,maxPh:7,maturityDays:1000,seasons:["Gu establishment"],color:"#65a30d",pathologies:[["Phytophthora Root Rot","Phytophthora cinnamomi","Sparse canopy; black feeder roots","Stop contaminated runoff","Use clean plants, drainage and integrated root-rot management."],["Avocado Anthracnose","Colletotrichum species","Sunken fruit lesions; postharvest rot","Remove infected fruit","Improve canopy hygiene and harvest handling."]]},
    date:{category:"Fruits",family:"Arecaceae",rootDepth:"Deep",nitrogenDemand:"Heavy Feeder",minPh:7,maxPh:8.5,maturityDays:1800,seasons:["Irrigated establishment"],color:"#92400e",pathologies:[["Bayoud Disease","Fusarium oxysporum f. sp. albedinis","Frond whitening; vascular streaks","Quarantine suspected palms","Use certified resistant offshoots and official diagnostics."],["Red Palm Weevil","Rhynchophorus ferrugineus","Oozing trunk holes; crown collapse","Trap adults and report infestations","Use sanitation and authority-approved integrated management."]]},
    guava:{category:"Fruits",family:"Myrtaceae",rootDepth:"Deep",nitrogenDemand:"Light Feeder",minPh:5,maxPh:7.5,maturityDays:680,seasons:["Gu","Deyr establishment"],color:"#4ade80",pathologies:[["Guava Wilt","Fusarium/Nalanthamala complex","Branch yellowing; vascular browning","Remove dead roots","Use clean stock and improve drainage."],["Fruit Fly","Bactrocera species","Fruit punctures; larvae","Destroy fallen fruit","Use bait stations and area-wide sanitation."]]},
    papaya:{category:"Fruits",family:"Caricaceae",rootDepth:"Medium",nitrogenDemand:"Heavy Feeder",minPh:5.5,maxPh:7,maturityDays:260,seasons:["Gu","Year-round irrigation"],color:"#f97316",pathologies:[["Papaya Ringspot Virus","PRSV","Rings on fruit; shoestring leaves","Rogue symptoms","Use clean tolerant plants and manage aphid vectors."],["Papaya Anthracnose","Colletotrichum species","Sunken fruit lesions; orange spores","Remove diseased fruit","Improve sanitation and protect fruit during wet periods."]]},
    grape:{category:"Fruits",family:"Vitaceae",rootDepth:"Deep",nitrogenDemand:"Heavy Feeder",minPh:5.5,maxPh:7,maturityDays:730,seasons:["Jilaal establishment"],color:"#7c3aed",pathologies:[["Grape Powdery Mildew","Erysiphe necator","White growth; berry cracking","Open canopy","Use sanitation and resistance-managed controls."],["Downy Mildew","Plasmopara viticola","Oil spots; white underside growth","Reduce leaf wetness","Use forecast-led integrated management."]]},
    pomegranate:{category:"Fruits",family:"Lythraceae",rootDepth:"Deep",nitrogenDemand:"Light Feeder",minPh:5.5,maxPh:7.5,maturityDays:700,seasons:["Gu establishment"],color:"#e11d48",pathologies:[["Bacterial Blight","Xanthomonas axonopodis pv. punicae","Oily leaf spots; fruit cracking","Prune infected twigs","Use clean cuttings and avoid overhead irrigation."],["Pomegranate Fruit Rot","Alternaria and related fungi","Internal fruit decay; rind spots","Remove mummified fruit","Improve sanitation and canopy airflow."]]},
    fig:{category:"Fruits",family:"Moraceae",rootDepth:"Deep",nitrogenDemand:"Light Feeder",minPh:6,maxPh:8,maturityDays:730,seasons:["Jilaal establishment"],color:"#7e22ce",pathologies:[["Fig Rust","Cerotelium fici","Rust spots; leaf drop","Remove fallen leaves","Improve airflow and use registered controls if severe."],["Fig Mosaic","Fig mosaic virus complex","Mosaic rings; distorted leaves","Use clean cuttings","Manage mite vectors and remove severe sources."]]},
    melon:{category:"Fruits",family:"Cucurbitaceae",rootDepth:"Medium",nitrogenDemand:"Heavy Feeder",minPh:5.8,maxPh:7.2,maturityDays:80,seasons:["Gu","Xagaa"],color:"#fcd34d",pathologies:[["Powdery Mildew","Podosphaera xanthii","White colonies; leaf decline","Improve airflow","Use tolerant cultivars and registered mildew controls."],["Fusarium Wilt","Fusarium oxysporum f. sp. melonis","Vine wilt; vascular browning","Remove vines","Use resistant varieties and rotation."]]},
  };
  const names={
    tomato:["Roma VF","Money Maker","Rio Grande","Marglobe","Cal J","Tengeru 97","Anna F1","Kilele F1","Assila F1","Shanty F1","Onyx","Cherry Sweet 100"],
    onion:["Red Creole","Bombay Red","Texas Grano","Jambar F1","Red Pinoy","Neptune F1","Safari F1","White Lisbon","Giza 6","Aqaba Red"],
    pepper:["California Wonder","Cayenne Long Slim","Bird's Eye","Scotch Bonnet","Jalapeño M","Serenade F1","Commandant F1","Habanero Red","Anaheim","Pusa Jwala"],
    cabbage:["Copenhagen Market","Gloria F1","Victoria F1","Drumhead","Red Acre","Oxylus F1","Pruktor F1","Sugarloaf"],
    carrot:["Nantes","Chantenay","Kuroda","New Kuroda","Amsterdam Forcing","Touchon","Nantes Improved","Atomic Red"],
    potato:["Shangi","Desiree","Kenya Mpya","Unica","Dutch Robijn","Markies","Arizona","Challenger"],
    sweetpotato:["Kabode","Vita","Beauregard","Ejumula","Naspot 1","Naspot 8","Irene","Kakamega"],
    cucumber:["Ashley","Poinsett 76","Marketmore 76","Palomar F1","Murano F1","Beth Alpha","Beit Alpha","Carmen F1"],
    watermelon:["Crimson Sweet","Sugar Baby","Charleston Gray","Sukari F1","Zuri F1","Kito F1","Sweet Rose F1","Jubilee"],
    pumpkin:["Waltham Butternut","Kent","Musquée de Provence","Connecticut Field","Queensland Blue","Jarrahdale"],
    eggplant:["Black Beauty","Long Purple","Kichawi F1","Ravaya F1","African Beauty","Listada de Gandia"],
    okra:["Clemson Spineless","Emerald Green","Pusa Sawani","Cajun Delight","Burgundy","Kirikou F1"],
    lettuce:["Great Lakes","Buttercrunch","Parris Island Cos","Green Oak Leaf","Lollo Bionda","Batavia"],
    spinach:["Fordhook Giant","Bloomsdale","Giant Nobel","Palco F1","New Zealand Spinach"],
    bean:["Rosecoco","Mwitemania","KAT B1","KAT B9","KAT X56","Red Haricot","Canadian Wonder","GLP 2"],
    pea:["Lincoln","Sugar Snap","Green Feast","Oregon Sugar Pod","Onward"],
    mango:["Apple","Ngowe","Boribo","Kent","Keitt","Tommy Atkins","Haden","Van Dyke","Sensation","Sabre","Dodo","Palmer"],
    banana:["East African Highland Matoke","Grand Nain","Williams","Dwarf Cavendish","Gros Michel","Sukari Ndizi","Kisii","FHIA-17","FHIA-25","Pisang Awak"],
    citrus:["Valencia Orange","Washington Navel","Jaffa Orange","Eureka Lemon","Lisbon Lemon","Tahiti Lime","Key Lime","Satsuma Mandarin","Clementine Nules","Murcott","Marsh Grapefruit","Star Ruby Grapefruit","Chandler Pomelo","Minneola Tangelo","Kinnow Mandarin"],
    avocado:["Hass","Fuerte","Puebla","Pinkerton","Reed","Bacon","Ettinger","Jumbo"],
    date:["Medjool","Ajwa","Barhi","Deglet Noor","Khalas","Sukkari","Khadrawy","Zahidi","Halawy","Dayri"],
    guava:["Allahabad Safeda","Ruby Supreme","Lucknow 49","Thai White","Red Malaysian","Crystal"],
    papaya:["Red Lady","Solo Sunrise","Tainung No. 1","Maradol","Waimanalo","Kapoho Solo"],
    grape:["Thompson Seedless","Flame Seedless","Crimson Seedless","Red Globe","Muscat of Alexandria","Italia","Superior Seedless","Autumn Royal"],
    pomegranate:["Wonderful","Hicaz","Acco","Mollar de Elche","Parfianka"],
    fig:["Brown Turkey","Black Mission","Kadota","Calimyrna","Adriatic"],
    melon:["Hales Best Cantaloupe","Honey Dew Green","Galia","Charentais","Canary Yellow","Piel de Sapo","Ananas","Ogen"],
  };
  const slug=s=>s.toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/[^a-z0-9]+/g,"_").replace(/^_|_$/g,"");
  const produce=Object.entries(names).flatMap(([profileKey,varieties])=>varieties.map(name=>{
    const p=profiles[profileKey];
    return {id:`shared_${profileKey}_${slug(name)}`,baseId:profileKey,name,category:p.category,categorySo:p.category==="Fruits"?"Midho":"Khudaar",family:p.family,rootDepth:p.rootDepth,nitrogenDemand:p.nitrogenDemand,minPh:p.minPh,maxPh:p.maxPh,maturityDays:p.maturityDays,seasons:p.seasons,color:p.color,pathologies:p.pathologies.map(x=>({disease:x[0],cause:x[1],symptoms:x[2].split("; "),immediate:[x[3]],remedy:x[4]})),region:"East Africa · Middle East"};}));
  const seedOils=[
    {id:"oil_sesame",name:"Sesame",family:"Pedaliaceae",minPh:5.5,maxPh:8,maturityDays:100,seasons:["Gu","Deyr"],rootDepth:"Deep",nitrogenDemand:"Light Feeder",pathologies:[["Sesame Phyllody","Phytoplasma · leafhopper vectored","Leafy flowers; capsule failure","Rogue affected plants","Use clean seed and manage weed hosts and leafhoppers."],["Sesame Charcoal Rot","Macrophomina phaseolina","Stem blackening; dry wilt","Remove residue","Rotate and reduce drought stress."]]},
    {id:"oil_palm",name:"Oil Palm",family:"Arecaceae",minPh:4,maxPh:7,maturityDays:1095,seasons:["Humid establishment"],rootDepth:"Deep",nitrogenDemand:"Heavy Feeder",pathologies:[["Basal Stem Rot","Ganoderma boninense","Basal decay; frond collapse","Remove confirmed palms","Use clean sites and sanitation."],["Fusarium Wilt","Fusarium oxysporum f. sp. elaeidis","Frond yellowing; vascular browning","Quarantine material","Use tolerant certified planting stock."]]},
    {id:"oil_sunflower",name:"Sunflower",family:"Asteraceae",minPh:6,maxPh:7.5,maturityDays:110,seasons:["Gu"],rootDepth:"Deep",nitrogenDemand:"Heavy Feeder",pathologies:[["Downy Mildew","Plasmopara halstedii","Pale leaves; systemic stunting","Remove systemic plants","Use resistant hybrids and treated seed where approved."],["Sclerotinia Rot","Sclerotinia sclerotiorum","Stem rot; head decay","Remove infected residue","Rotate broadleaf hosts and manage canopy humidity."]]},
    {id:"oil_castor",name:"Castor",family:"Euphorbiaceae",minPh:5.5,maxPh:7.5,maturityDays:150,seasons:["Gu"],rootDepth:"Deep",nitrogenDemand:"Light Feeder",pathologies:[["Castor Gray Mold","Botryotinia ricini","Capsule mold; seed rot","Remove infected racemes","Use spacing and clean seed."],["Fusarium Wilt","Fusarium oxysporum f. sp. ricini","Wilt; vascular browning","Remove affected plants","Use resistant material and rotation."]]},
    {id:"oil_niger",name:"Niger Seed (Noug)",family:"Asteraceae",minPh:5.2,maxPh:7.5,maturityDays:120,seasons:["Gu","Highland rains"],rootDepth:"Medium",nitrogenDemand:"Light Feeder",pathologies:[["Niger Leaf Spot","Alternaria species","Dark leaf lesions; defoliation","Remove residue","Use clean seed and rotation."],["Niger Wilt","Fusarium species","Patchy wilt; vascular discoloration","Remove plants","Rotate and improve drainage."]]},
    {id:"oil_olive",name:"Olive",family:"Oleaceae",minPh:6.5,maxPh:8.5,maturityDays:1460,seasons:["Jilaal establishment"],rootDepth:"Deep",nitrogenDemand:"Light Feeder",pathologies:[["Olive Leaf Spot","Venturia oleaginea","Dark peacock spots; leaf drop","Prune canopy","Use sanitation and registered copper guidance."],["Olive Knot","Pseudomonas savastanoi","Woody galls; dieback","Prune dry and sanitize tools","Avoid wounds and use clean stock."]]},
    {id:"oil_jojoba",name:"Jojoba",family:"Simmondsiaceae",minPh:6,maxPh:8.5,maturityDays:1095,seasons:["Dry irrigated establishment"],rootDepth:"Deep",nitrogenDemand:"Light Feeder",pathologies:[["Jojoba Root Rot","Phytophthora species","Root decay; wilt","Correct drainage","Use clean stock and avoid over-irrigation."],["Alternaria Leaf Spot","Alternaria species","Brown leaf spots; defoliation","Remove residue","Improve airflow and monitor."]]},
  ].map(item=>Object.assign({category:"Seed Oil",categorySo:"Saliidda Abuurka",color:"#d97706",region:"Africa · Middle East"},item,{pathologies:item.pathologies.map(x=>({disease:x[0],cause:x[1],symptoms:x[2].split("; "),immediate:[x[3]],remedy:x[4]}))}));
  const trees=[
    ["tree_moringa","Moringa","Moringaceae"],["tree_neem","Neem","Meliaceae"],["tree_acacia_senegal","Gum Arabic Acacia","Fabaceae"],["tree_boswellia","Frankincense Tree","Burseraceae"],["tree_myrrh","Myrrh Tree","Burseraceae"],["tree_tamarind","Tamarind Tree","Fabaceae"],["tree_jujube","Jujube Tree","Rhamnaceae"],
  ].map(([id,name,family])=>({id,name,category:"Tree",categorySo:"Geedaha",family,rootDepth:"Deep",nitrogenDemand:family==="Fabaceae"?"Nitrogen Fixer":"Light Feeder",minPh:6,maxPh:8.5,maturityDays:1460,seasons:["Gu establishment"],color:"#15803d",region:"East Africa",pathologies:[{disease:"Root and Collar Rot",cause:"Soil-borne fungal/oomycete complex",symptoms:["Root decay","Canopy decline"],immediate:["Improve drainage"],remedy:"Use clean stock and confirm the causal organism."},{disease:"Canker and Dieback",cause:"Opportunistic fungal/bacterial complex",symptoms:["Branch dieback","Bark lesions"],immediate:["Prune dry and sanitize tools"],remedy:"Reduce stress and protect wounds."}]}));
  global.AGRI_SHARED={version:"2026.08-regional-200",minimumRegionalCount:200,regionalProduceCount:produce.length,i18n:I18N,produce,seedOils,trees,catalog:produce.concat(seedOils,trees),t:function(lang,key){return (I18N[lang]&&I18N[lang][key])||I18N.en[key]||key;}};
})(window);
